apiVersion: v1
kind: Service
metadata:
  name: mediagent-service
  labels:
    app: mediagent
spec:
  type: LoadBalancer
  selector:
    app: mediagent
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  sessionAffinity: None
